/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.io.IOException;
import java.util.Scanner;

import org.example.HTTP.Cliente;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws IOException {
        Scanner leitor = new Scanner(System.in);
        System.out.print("Digite um ip: ");
        String ip = leitor.next();
        System.out.println(ip);

        Cliente clienteHTTP = new Cliente(ip, 0);

        boolean running = true;
        System.out.println("Digite uma mensagem: ");

        while (running) {
            String mensagem = leitor.next();
            String resposta = clienteHTTP.envia(mensagem);
            if (!resposta.contains("status 3")) {
                running = false;
            }
            System.out.println("Digite uma mensagem: ");
            running = false;

        }
        leitor.close();
    }
}
