/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.net.http.HttpResponse.BodyHandlers;
import java.util.Scanner;


public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws IOException, InterruptedException, URISyntaxException {
        Scanner leitor = new Scanner(System.in);
        System.out.print("Digite um ip: ");
        String ip = leitor.nextLine();

        HttpClient cliente = HttpClient.newHttpClient();
        HttpRequest request = HttpRequest.newBuilder(new URI(ip)).GET().build();
        HttpResponse<String> response = cliente.send(request, BodyHandlers.ofString());
        System.out.printf("Status: %d\n", response.statusCode());
        System.out.printf("Corpo: %s\n", response.body());

    }
}
